class CreateAccountLocators:
    FIRST_NAME = '#firstname'
    LAST_NAME = '#lastname'
    EMAIL = '#email_address'
    PASSWORD = '#password'
    CONFIRM_PASSWORD = '#password-confirmation'
    CREATE_ACCOUNT_BUTTON = 'button:has-text("Create an Account")'
    SUCCESS_MESSAGE = 'div.message-success'
    FIRST_NAME_ERROR = '#firstname-error'
    LAST_NAME_ERROR = '#lastname-error'
    EMAIL_ERROR = '#email_address-error'
    PASSWORD_ERROR = '#password-error'
    CONFIRM_PASSWORD_ERROR = '#password-confirmation-error'
